### PR TITLE
adding non blocking execution

### PR DESCRIPTION
**Pull request by a-marcel**
It is possible to add this ? It's adding a nicer way to have a "syncron" Datafetcher wich one not blocks the eventbus. its for the ticket #7

### CODE REVIEW

**Comment by aschrijver** [comment]
Thanks Marcel, for this PR.

Sorry for the late response, but Github does not provide email notification on changes of organization repo's, so I overlooked your PR.
I have created a new [`async-graphql`](https://github.com/engagingspaces/vertx-graphql-service-discovery/tree/async-graphql) branch in which I have merged your PR. I will keep that branch until the `4.0.0` release of GraphQL which supports async execution ootb.

**Comment by LeeWong** [comment]
Graphql-java 4.2 is released. https://github.com/graphql-java/graphql-java/releases

**Comment by aschrijver** [comment]
thanks @LeeWong 

i created an issue for upgrading #9

unfortunately i am awfully busy with my new tech startup called innercircles ...
a movement for aspiring holistic lifestyle hackers that care about the world

but if you could PR and have all tests pass, i'll be ready to merge..

**Comment by a-marcel** [comment]
I guess my solution is deprecated with graphql java 4.x now.

**Comment by a-marcel** [comment]
The final Fix is in #10 now

**Comment by aschrijver** [comment]
merged and available as `0.10.0`

**Pull request closed without merging**
