### PR TITLE
use new async java graphql execution

### PR DESCRIPTION
**Pull request by a-marcel**
Working Version with new GraphQL Java

### CODE REVIEW

**Comment by aschrijver** [comment]
@marcelalburg thanks for the update, Marcel!

did you look at the reason for the failing test?
unfortunately i am still too busy getting to look myself :)

`io.engagingspaces.graphql.servicediscovery.client.GraphQLClientTest > should_Fail_Execute_Query_With_Required_Variable_Missing FAILED`

**Comment by a-marcel** [comment]
Yes i'll, today. Yesterday it was to late in the night. Thanks

**Comment by a-marcel** [comment]
The "error" is not in my PR, it's in the new version of GraphQL. I'll take a deeper look.

**Comment by a-marcel** [comment]
I ask them.

https://github.com/graphql-java/graphql-java/issues/720

we'll see ...

**Comment by a-marcel** [comment]
We need to wait for the next graphql version, the bug is inside the v4.2.

**Comment by aschrijver** [comment]
thanks for your efforts @marcelalburg 
much appreciated :+1:

**Comment by LeeWong** [comment]
any update on this PR?

**Comment by a-marcel** [comment]
Yes, we need to wait for the next java-graphql version and after that, i'll finish this PR. There is a small but in the current java-graphql version.

Marcel

**Comment by a-marcel** [comment]
In the new version, they throwing a different exception with a new message. So i would suggest to increase to the next major version to make this change visible. 

I hope you will accept it and release a new version

Thanks
Marcel

**Comment by a-marcel** [comment]
@aschrijver: it is possible to release this version - maybe 0.10.0 ?

**Comment by aschrijver** [comment]
hi @marcelalburg 

great! so everything is ready?
i will review and merge this weekend.. am awfully busy atm 

thanks a bunch for your efforts :+1:

**Comment by a-marcel** [comment]
Yes, from my side, everything is ready. 

Thanks a lot.

**Pull request merged**
